### PR TITLE
Add method to get all trash paths

### PR DESCRIPTION
**Pull request by kevva**
I don't know if this is totally correct. Should we filter out all the non-existing dirs maybe @sindresorhus? Else we get some very random paths back.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Should we filter out all the non-existing dirs maybe

Yes

-

// @tborychowski Can you review?

**Comment by kevva** [comment]
Aight, it'll filter out the non-existing directories now.

**Comment by sindresorhus** [comment]
Actually, when thinking about more. This the filtering should be done in `empty-trash`. This module should return all trash directories as that's what I would expect.

**Comment by tborychowski** [comment]
:+1: lgtm. 
@kevva, I think it might be good to add some comments here and there :-)
(i.e.: not "what" the line does what it does but "why")

**Comment by tborychowski** [comment]
@sindresorhus, but this module should still filter out the non-existing trash folders.
I mean - your `df` module (in my system) returns a lot of disks that don't have the trash folder, right?

**Comment by kevva** [comment]
> Actually, when thinking about more. This the filtering should be done in empty-trash. This module should return all trash directories as that's what I would expect.

@sindresorhus, yeah, but some of the directories would never even exist, (`/run/lock/.Trash-1000`) for example.

**Comment by sindresorhus** [comment]
> yeah, but some of the directories would never even exist, (/run/lock/.Trash-1000) for example. I don't know if it does any good to return those.

Yes, but it should return paths for any place a trash could be, even if it's not already there.

**Comment by kevva** [comment]
My point is that a trash can't exist at some of those paths.

**Comment by kevva** [comment]
Ah well, shouldn't hurt anyway. I'll just return all.

**Comment by sindresorhus** [comment]
> My point is that a trash can't exist at some of those paths.

Yes, I got that. But we should return the path to the trash in e.g. an external HDD even though it doesn't exist yet.

**Pull request merged**
